name: update flakes
on:
  schedule:
    - cron:  '* 10 * * *'
  workflow_dispatch:
jobs:
  update-flakes:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          repository: lovesegfault/nix-config
          token: ${{ secrets.PAT }}
      - uses: cachix/install-nix-action@v12
        with:
          install_url: https://github.com/numtide/nix-flakes-installer/releases/download/nix-2.4pre20201221_9fab14a/install
          extra_nix_config: "experimental-features = nix-command flakes"
      - uses: cachix/cachix-action@v8
        with:
          name: nix-config
          signingKey: '${{ secrets.CACHIX_SIGNING_KEY }}'
      - run: git config --global user.email "bernardo@meurer.org"
      - run: git config --global user.name "Bernardo Meurer"
      - name: Update flakes
        run: nix flake update --recreate-lock-file --commit-lock-file
      - uses: peter-evans/create-pull-request@v3
        with:
          branch: flake-update
          commit-message: "flake: update"
          delete-branch: true
          title: "flake: update"
          token: ${{ secrets.PAT }}
